name: build

on:
  workflow_run:
    workflows: ["test"]  # This should match the name field in test.yml
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: arc-runner-set
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
    - 
      name: Build
      run: go build -v ./...
